#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Set up the systemd --user timer that drives the Hermes perf poller.

Generates hermes-perf.service + hermes-perf.timer in ~/.config/systemd/user/,
reloads systemd, and enables the timer. Safe to re-run -- e.g. to change the
polling interval or the poller's flags.

Anything after a `--` is passed through verbatim to poll-and-bench.py and baked
into the service's ExecStart:

    python3 setup-systemd.py                       # 15-min interval, enable now
    python3 setup-systemd.py --interval-min 30
    python3 setup-systemd.py --linger              # survive logout (headless Pi)
    python3 setup-systemd.py --write-only          # write unit files only
    python3 setup-systemd.py -- --reps 10          # poller args after --
"""

import argparse
import os
import pwd
import shlex
import subprocess
import sys
from pathlib import Path

SERVICE_NAME = "hermes-perf.service"
TIMER_NAME = "hermes-perf.timer"

SERVICE_TEMPLATE = """\
# Generated by setup-systemd.py -- do not edit; re-run the script instead.
[Unit]
Description=Hermes perf: poll for new builds, benchmark, publish results
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart={exec_start}

[Install]
WantedBy=default.target
"""

TIMER_TEMPLATE = """\
# Generated by setup-systemd.py -- do not edit; re-run the script instead.
[Unit]
Description=Poll for new Hermes builds to benchmark every {interval} minutes

[Timer]
# First poll shortly after boot, then every {interval} minutes after each run.
OnBootSec=2min
OnUnitActiveSec={interval}min
# Run once on next boot if a fire was missed while the Pi was off.
Persistent=true
Unit={service}

[Install]
WantedBy=timers.target
"""


def run(cmd, check=True):
    print("+ " + " ".join(cmd))
    return subprocess.run(cmd, check=check)


def main():
    # Split our own args from poller passthrough args (everything after `--`).
    argv = sys.argv[1:]
    if "--" in argv:
        sep = argv.index("--")
        own_argv, poller_args = argv[:sep], argv[sep + 1 :]
    else:
        own_argv, poller_args = argv, []

    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--interval-min",
        type=int,
        default=15,
        metavar="N",
        help="minutes between polls (default: 15)",
    )
    ap.add_argument(
        "--linger",
        action="store_true",
        help="run 'loginctl enable-linger' so the timer fires without an "
        "active login session (needed on a headless Pi)",
    )
    ap.add_argument(
        "--write-only",
        action="store_true",
        help="write the unit files but skip daemon-reload/enable",
    )
    args = ap.parse_args(own_argv)

    if args.interval_min < 1:
        sys.exit("--interval-min must be >= 1")

    # This script lives at <data-repo>/main/runner/setup-systemd.py.
    runner_dir = Path(__file__).resolve().parent
    poller = runner_dir / "poll-and-bench.py"
    if not poller.exists():
        sys.exit(f"poller not found: {poller}")

    # Invoke the poller through this same Python; append any passthrough flags.
    exec_start = " ".join(
        shlex.quote(part) for part in [sys.executable, str(poller), *poller_args]
    )

    unit_dir = Path.home() / ".config" / "systemd" / "user"
    unit_dir.mkdir(parents=True, exist_ok=True)

    (unit_dir / SERVICE_NAME).write_text(SERVICE_TEMPLATE.format(exec_start=exec_start))
    (unit_dir / TIMER_NAME).write_text(
        TIMER_TEMPLATE.format(interval=args.interval_min, service=SERVICE_NAME)
    )
    print(f"Wrote {unit_dir / SERVICE_NAME}")
    print(f"  ExecStart={exec_start}")
    print(f"Wrote {unit_dir / TIMER_NAME}  (every {args.interval_min} min)")

    if args.write_only:
        print("--write-only: skipping daemon-reload/enable.")
        return

    run(["systemctl", "--user", "daemon-reload"])
    run(["systemctl", "--user", "enable", "--now", TIMER_NAME])

    if args.linger:
        user = pwd.getpwuid(os.getuid()).pw_name
        if run(["loginctl", "enable-linger", user], check=False).returncode != 0:
            print(
                f"WARNING: 'loginctl enable-linger {user}' failed; "
                f"re-run with: sudo loginctl enable-linger {user}"
            )

    run(["systemctl", "--user", "list-timers", TIMER_NAME], check=False)
    print("\nDone. Inspect logs with: journalctl --user -u hermes-perf.service -f")


if __name__ == "__main__":
    main()
